create database Project2;
use Project2;
select * from my_table;
-- Q1 what is the total revenew generated by male vs female customer ?
select gender,sum(purchase_amount) as revenue
from my_table
group by gender;
-- Q2. Mhich customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from my_table
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount) from my_table);
-- 03. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating), 2) AS `Average Product Rating`
FROM my_table
GROUP BY item_purchased
ORDER BY `Average Product Rating` DESC
LIMIT 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,ROUND(AVG(purchase_amount), 2) #AS avg_purchase_amount,COUNT(*) AS total_orders
FROM my_table
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,ROUND(AVG(purchase_amount), 2) AS avg_spend_per_customer,
    SUM(purchase_amount) AS total_revenue,
    COUNT(DISTINCT customer_id) AS unique_customers
FROM my_table
GROUP BY subscription_status;

-- Q6. Which $ products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
    COUNT(*) AS total_purchases,SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 
        2
    ) AS discount_percentage
FROM my_table
GROUP BY item_purchased
HAVING COUNT(*) > 0
ORDER BY discount_percentage DESC
LIMIT 10;


SELECT item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100,
        2
    ) AS discount_rate
FROM my_table
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

SELECT 
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        WHEN previous_purchases > 5 THEN 'Loyal'
    END AS customer_segment,
    COUNT(DISTINCT customer_id) AS customer_count
FROM my_table
GROUP BY customer_segment
ORDER BY customer_count DESC;
-- Q8. What are the top 3 most purchased products within each category?
SELECT 
    category,
    item_purchased,
    total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM my_table
    GROUP BY category, item_purchased
) AS ranked
WHERE product_rank <= 3
ORDER BY category,
total_purchases DESC;

-- 09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS customer_type,
    subscription_status,
    COUNT(DISTINCT customer_id) AS customer_count,
    ROUND(
        (COUNT(DISTINCT customer_id) / SUM(COUNT(DISTINCT customer_id)) OVER (PARTITION BY CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer' ELSE 'Non-Repeat Buyer' END)) * 100,
        2
    ) AS percent_subscribed
FROM my_table
GROUP BY customer_type, subscription_status
ORDER BY customer_type, subscription_status;

-- Q10. What is the revenue contribution of each age goup?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        (SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM my_table)) * 100,
        2
    ) AS revenue_percentage
FROM my_table
GROUP BY age_group
ORDER BY revenue_percentage DESC;
SELECT DATABASE() AS current_database;

